### PR TITLE
Fix broken pipe errors caused by a race condition in the daemon.

### LINKED ISSUE #167: flush_writebuf() failed Broken pipe
I am running the latest master on MacOS; almost everything seems to be working for me now, launching on the master (192.168.0.1):

```
$ sudo icecc-scheduler -n frutti -u daemon -vvv
$ sudo iceccd -n frutti -m 3 -vvv -s localhost -N skree -u daemon
```

and on the slave (192.168.0.2):

```
$ sudo iceccd -n frutti -m 3 -vvv -s 192.168.0.1 -N wingy -u daemon
```

But although the slave shakes hands and even gets the environment from the master, it never seems to actually build anything.  My build command output is full of these:

```
ICECC[39986] 16:56:08: flush_writebuf() failed Broken pipe
ICECC[39986] 16:56:08: write of source chunk to host 192.168.0.2
ICECC[39986] 16:56:08: failed  Broken pipe
ICECC[39986] 16:56:08: got exception Error 15 - write to host failed (192.168.0.2) 
```

and my slave log looks like this:

```
[2909] 16:55:12: ICECREAM daemon 1.1rc2 starting up (nice level 5) 
[2909] 16:55:12: 8 CPU(s) online on this server
[2909] 16:55:12: allowing up to 10 active jobs
[2909] 16:55:12: not detaching
[2909] 16:55:12: entered process group
[2909] 16:55:12: ignoring localhost lo0
[2909] 16:55:12: broadcast en0 17.114.131.255
[2909] 16:55:12: broadcast bridge0 192.168.0.255
[2909] 16:55:12: Netnames:
[2909] 16:55:12: frutti
[2909] 16:55:12: scheduler is on 192.168.0.1:8765 (net )
[2909] 16:55:12: scheduler not yet found.
[2909] 16:55:15: scheduler not yet found.
[2909] 16:55:18: Connected to scheduler (I am known as 192.168.0.2)
[2909] 16:55:44: accepted 7 192.168.0.1
[2909] 16:55:44: handle_transfer_env
[2909] 16:55:44: pid 2910
[2909] 16:55:44: got pid 2910
[2909] 16:55:44: handle_transfer_env_done
[2909] 16:55:44: installed_size: 59830408
[2909] 16:55:44: installed Darwin16_x86_64/fc70ec139a0b6f7f67e5f0a262357823 size: 59830408 all: 59830408
[2909] 16:55:44: reannounce_environments 
[2909] 16:55:44: Verify environment done, success, environment fc70ec139a0b6f7f67e5f0a262357823 (Darwin16_x86_64)
[2909] 16:55:44: requests--1
[2909] 16:55:44: handle connection returned 2912
[2912] 23:55:44: <parent, waiting>
[2912] 23:55:44: timeout <= 0
[2912] 23:55:44: !wait_for_msg()
[2912] 23:55:44: timeout <= 0
[2912] 23:55:44: !wait_for_msg()
[2912] 23:55:44: timeout <= 0
[2912] 23:55:44: !wait_for_msg()
[2912] 23:55:44: timeout <= 0
[2912] 23:55:44: !wait_for_msg()
[2912] 23:55:44: </parent, waiting: 20ms>
[2909] 16:55:45: accepted 7 192.168.0.1
[2909] 16:55:45: requests--7
[2909] 16:55:45: handle connection returned 2914
[2914] 23:55:45: <parent, waiting>
[2914] 23:55:45: timeout <= 0
[2914] 23:55:45: !wait_for_msg()
[2914] 23:55:45: timeout <= 0
[2914] 23:55:45: !wait_for_msg()
[2914] 23:55:45: timeout <= 0
[2914] 23:55:45: !wait_for_msg()
[2914] 23:55:45: timeout <= 0
[2914] 23:55:45: !wait_for_msg()
[2914] 23:55:45: </parent, waiting: 14ms>
[2909] 16:55:45: accepted 7 192.168.0.1
[2909] 16:55:45: requests--14
[2909] 16:55:45: handle connection returned 2916
[2916] 23:55:45: <parent, waiting>
[2916] 23:55:45: timeout <= 0
[2916] 23:55:45: !wait_for_msg()
[2916] 23:55:45: timeout <= 0
[2916] 23:55:45: !wait_for_msg()
[2916] 23:55:45: timeout <= 0
[2916] 23:55:45: !wait_for_msg()
[2916] 23:55:45: timeout <= 0
[2916] 23:55:45: !wait_for_msg()
[2916] 23:55:45: </parent, waiting: 14ms>
[2909] 16:55:46: accepted 7 192.168.0.1
[2909] 16:55:46: requests--16
...etc...
```

Any help would be most appreciated!

### PR DESCRIPTION
**Pull request by creste**
This pull request fixes #167. @johnmiked15's comment at https://github.com/icecc/icecream/issues/167#issuecomment-287121377 provides a good description of the problem.

I saw two different ways to fix the problem.  One way to fix it was to modify the client to allow the daemon to send a CompileResult message before the client was finished sending all file data to the daemon.  That would have required significant changes on the client side and would have been much harder for me to test.

The second way to fix it was to modify the daemon to adhere to the protocol expectations set by the client.  Specifically, the daemon should not close the socket or attempt to send a CompileResult message until the client has finished sending all file data to the daemon.  I chose this route because it was much easier to test and required minimal changes in the daemon.

I made two logical changes to the daemon.  The first change was to make the daemon wait for all
file input to be received from the client before it checks to see if the compiler terminated.  Waiting for all file input makes sure the client is in a state where it is ready to receive a CompileResult.

The second change was to make the daemon detect when the compiler terminates before file input is received and treat that as a normal termination, instead of a crash, so that stdout and stderr can be sent back to the client in the CompileResult message.  You can see that on line 525 where the daemon checks if input is complete before setting the exit status to `EXIT_COMPILER_CRASHED`.

The easiest way for me to reproduce this problem was to try to compile an objective-C file using clang 3.6 on Mac while also passing in `-ObjC` and `-Werror`.  This was causing clang to return an error before it tried to read the input file on stdin because the daemon was adding `-x` and clang prints a warning when `-x` is passed with `-ObjC`, which was being converted to an error due to `-Werror`.  I'm guessing that since clang detected the error in the command line arguments it had no reason to try to read the file from stdin.

### CODE REVIEW

**Comment by HenryMiller1** [comment]
Can you turn your reproduction into a test?  I'm fine with a test that only works on MacOS (perhaps a different script as I don't think the other tests work on MacOS).  It looks like you already have the steps required, so just automate that somehow.

File: daemon/workit.cpp [hunk 1]
```diff
@@ -501,11 +522,13 @@ int work_it(CompileJob &j, unsigned int job_stat[], MsgChannel *client, CompileR
...
-                    return_value = EXIT_COMPILER_CRASHED;
-                    client_fd = -1;
-                    input_complete = true;
+                    if (input_complete) {
+                        return_value = EXIT_COMPILER_CRASHED;
+                    }
                     delete fcmsg;
                     fcmsg = 0;
+                    close(sock_in[1]);
+                    sock_in[1] = -1;
```
Comment (HenryMiller1) [inline daemon/workit.cpp]: Instead of negative one as a hard coded number use `#define COMPILED_CRASH_SOCKET_CLOSED -1` someplace and reference that here.  I'd probably use sock_in[in] <0 as the check for error condition elsewhere.

File: daemon/workit.cpp [hunk 2]
```diff
@@ -382,7 +382,7 @@ int work_it(CompileJob &j, unsigned int job_stat[], MsgChannel *client, CompileR
                     if (msg->type == M_END) {
                         input_complete = true;
 
-                        if (!fcmsg) {
+                        if (!fcmsg && sock_in[1] != -1) {
                             close(sock_in[1]);
                             sock_in[1] = -1;
```
Comment (HenryMiller1) [inline daemon/workit.cpp]: As below, use a constant

**Comment by HenryMiller1** [comment]
Looks good in general.

**Comment by creste** [comment]
Hi @HenryMiller1, thank you for the feedback.  Unfortunately I can't get unit tests in the **master** branch to work on any platform.  Can you please tell me which OS and compiler versions the tests are supposed to work on?

I get a segmentation fault when running the unit tests on Darwin 12.5.0:
```
Running make test 1.
./test.sh: line 419: 43611 Segmentation fault: 11  ICECC_TEST_SOCKET="$testdir"/socket-localice $valgrind "$prefix"/sbin/iceccd --no-remote -s localhost:8767 -b "$testdir"/envs-localice -l "$testdir"/localice.log -N localice -m 2 -v -v -v
Make test 1 failed.
make[2]: *** [test-run] Error 2
make[1]: *** [test-full] Error 2
make: *** [test] Error 2
```

I get a clang compiler error when compiling clangplugin.cpp on Gentoo using clang 3.3:

```
g++ -shared -fPIC -o clangplugin.so clangplugin.cpp -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti
g++ -g -W -Wall -Wpointer-arith -Wcast-align  -Wwrite-strings -g -O2    clangplugin.cpp clangplugin.so   -o clangplugin
In file included from /usr/include/llvm/Support/type_traits.h:20:0,
                 from /usr/include/llvm/Support/Casting.h:18,
                 from /usr/include/clang/Basic/LLVM.h:22,
                 from /usr/include/clang/AST/APValue.h:17,
                 from /usr/include/clang/AST/Decl.h:17,
                 from /usr/include/clang/AST/ASTTypeTraits.h:18,
                 from /usr/include/clang/AST/ASTContext.h:18,
                 from clangplugin.cpp:12:
/usr/include/llvm/Support/DataTypes.h:49:3: error: #error "Must #define __STDC_LIMIT_MACROS before #including Support/DataTypes.h"
 # error "Must #define __STDC_LIMIT_MACROS before #including Support/DataTypes.h"
   ^
/usr/include/llvm/Support/DataTypes.h:53:3: error: #error "Must #define __STDC_CONSTANT_MACROS before " "#including Support/DataTypes.h"
 # error "Must #define __STDC_CONSTANT_MACROS before " \
   ^
```

I get a different compiler error when compiling on Gentoo using clang 3.9:

```
g++ -shared -fPIC -o clangplugin.so clangplugin.cpp -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti
clangplugin.cpp:32:30: error: conflicting return type specified for ‘virtual clang::ASTConsumer* IcecreamTest::Action::CreateASTConsumer(clang::CompilerInstance&, llvm::StringRef)’
         virtual ASTConsumer* CreateASTConsumer( CompilerInstance& compiler, StringRef infile );
                              ^~~~~~~~~~~~~~~~~
In file included from clangplugin.cpp:15:0:
/usr/include/clang/Frontend/FrontendAction.h:241:32: error:   overriding ‘virtual std::unique_ptr<clang::ASTConsumer> clang::PluginASTAction::CreateASTConsumer(clang::CompilerInstance&, llvm::StringRef)’
   std::unique_ptr<ASTConsumer> CreateASTConsumer(CompilerInstance &CI,
                                ^~~~~~~~~~~~~~~~~
clangplugin.cpp: In function ‘void IcecreamTest::report(const clang::CompilerInstance&, clang::DiagnosticsEngine::Level, const char*, clang::SourceLocation)’:
clangplugin.cpp:118:64: error: no matching function for call to ‘clang::DiagnosticsEngine::getCustomDiagID(clang::DiagnosticsEngine::Level&, const char*&)’
         engine.Report( loc, engine.getCustomDiagID( level, txt ));
                                                                ^
In file included from /usr/include/clang/Basic/PartialDiagnostic.h:19:0,
                 from /usr/include/clang/AST/DeclarationName.h:17,
                 from /usr/include/clang/AST/DeclBase.h:18,
                 from /usr/include/clang/AST/Decl.h:18,
                 from /usr/include/clang/AST/ASTTypeTraits.h:20,
                 from /usr/include/clang/AST/ASTContext.h:18,
                 from clangplugin.cpp:12:
/usr/include/clang/Basic/Diagnostic.h:609:12: note: candidate: template<unsigned int N> unsigned int clang::DiagnosticsEngine::getCustomDiagID(clang::DiagnosticsEngine::Level, const char (&)[N])
   unsigned getCustomDiagID(Level L, const char (&FormatString)[N]) {
            ^~~~~~~~~~~~~~~
/usr/include/clang/Basic/Diagnostic.h:609:12: note:   template argument deduction/substitution failed:
clangplugin.cpp:118:64: note:   mismatched types ‘const char [N]’ and ‘const char*’
         engine.Report( loc, engine.getCustomDiagID( level, txt ));
                                                                ^
clangplugin.cpp:120:59: error: no matching function for call to ‘clang::DiagnosticsEngine::getCustomDiagID(clang::DiagnosticsEngine::Level&, const char*&)’
         engine.Report( engine.getCustomDiagID( level, txt ));
                                                           ^
In file included from /usr/include/clang/Basic/PartialDiagnostic.h:19:0,
                 from /usr/include/clang/AST/DeclarationName.h:17,
                 from /usr/include/clang/AST/DeclBase.h:18,
                 from /usr/include/clang/AST/Decl.h:18,
                 from /usr/include/clang/AST/ASTTypeTraits.h:20,
                 from /usr/include/clang/AST/ASTContext.h:18,
                 from clangplugin.cpp:12:
/usr/include/clang/Basic/Diagnostic.h:609:12: note: candidate: template<unsigned int N> unsigned int clang::DiagnosticsEngine::getCustomDiagID(clang::DiagnosticsEngine::Level, const char (&)[N])
   unsigned getCustomDiagID(Level L, const char (&FormatString)[N]) {
            ^~~~~~~~~~~~~~~
/usr/include/clang/Basic/Diagnostic.h:609:12: note:   template argument deduction/substitution failed:
clangplugin.cpp:120:59: note:   mismatched types ‘const char [N]’ and ‘const char*’
         engine.Report( engine.getCustomDiagID( level, txt ));
                                                           ^
Makefile:993: recipe for target 'clangplugin.so' failed
```

And I get a test failure when running the unit tests on Ubuntu 14.04:

```
Running: /usr/bin/g++ -Wall -Werror -gsplit-dwarf -g -c plain.cpp -o /home/myuser/code/icecream/tests/results/plain.o
Files /home/myuser/code/icecream/tests/results/plain.o.remote.readelf.txt and /home/myuser/code/icecream/tests/results/plain.o.readelf.txt differ
Output mismatch (/home/myuser/code/icecream/tests/results/plain.o.remoteice)
make[2]: *** [test-run] Error 2
make[2]: Leaving directory `/home/myuser/code/icecream/tests'
make[1]: *** [test-full] Error 2
make[1]: Leaving directory `/home/myuser/code/icecream/tests'
make: *** [test] Error 2

```

This is a diff of the two files:

```
--- tests/results/plain.o.remote.readelf.txt    2017-04-03 13:52:36.564565802 -0500
+++ tests/results/plain.o.readelf.txt   2017-04-03 13:52:36.564565802 -0500
@@ -1,7 +1,7 @@
 Contents of the .debug_info section:

   Compilation Unit @ offset 0x0:
-   Length:        0x5b (32-bit)
+   Length:        0x7c (32-bit)
    Version:       4
    Abbrev Offset: 0x0
    Pointer Size:  8
@@ -12,8 +12,8 @@
     <20>
     <28>
     <49>
-    <5b>   DW_AT_GNU_pubnames: 1
-    <5b>   DW_AT_GNU_addr_base: 0x0
+    <7c>   DW_AT_GNU_pubnames: 1
+    <7c>   DW_AT_GNU_addr_base: 0x0

 Contents of the .debug_abbrev section:

@@ -34,17 +34,17 @@
   Length:                              20
   Version:                             2
   Offset into .debug_info section:     0x0
-  Size of area in .debug_info section: 264
+  Size of area in .debug_info section: 165

     Offset     Name
-    f1         f
+    8e         f

 Contents of the .debug_pubtypes section:

   Length:                              14
   Version:                             2
   Offset into .debug_info section:     0x0
-  Size of area in .debug_info section: 264
+  Size of area in .debug_info section: 165

     Offset     Name

```

**Comment by HenryMiller1** [comment]
I'm told the tests pass in ubuntu 16.04.  I don't have that version to work with though.

The tests don't work in 14.04 - I get the same error you get: I'm working on fixing it. My goal right now issue #195, to fix that I need the tests in ubuntu 14.04 - probably by the end of the month. I'm not aware of any free ci system that makes 

I'm even fine with an all new test suite for OSX that only runs one test. If you get even one test to pass on OSX I will be happy to make running tests on OSX part of the CI suite.

I'm inclined to merge this as is though.  I'm just giving it a little longer to see if someone smarter than me can see an objection I do not.

File: daemon/workit.cpp (hunk 1 above)
Comment (ossilator) [inline daemon/workit.cpp]: bah, this makes the code _less_ readable imo. -1 is a very well established magic number for invalid file descriptors, being the error indicator value of almost all related stdlib functions. also, it's much quicker to read.

Comment (creste) [inline daemon/workit.cpp]: Generally speaking, I agree with @HenryMiller1 and I prefer to use constants instead of magic numbers like -1.  However, I chose not to use a constant in this commit because the existing code was using -1 and I thought maintaining that consistency was important.  I also thought that cleaning up the existing code to use a named constant was outside the scope of this bug fix and should be done in a separate PR, if at all.

May I suggest using -1 for this commit for now?  You two can discuss and do a full cleanup of the existing code in a separate PR if a named constant is preferred over -1.

**Comment by creste** [comment]
I don't have access to Ubuntu 16.04 at this time.  I'll see if I can get something working Mac by skipping all of the existing tests.  If you get the tests working on 14.04 before I start then I'll probably switch to that instead because I'm more familiar with Ubuntu than OS X.

Overall I'd feel much better about this PR if I could get unit tests working on at least one platform to make sure this change doesn't cause a regression.

**Comment by HenryMiller1** [comment]
Tests can be added at any time.
